### PR TITLE
🔥 Merge Notebooks 17 and 19 

### LINKED ISSUE #34: [URGENT] Merge Chapter 17 to 19 into one notebook on LLM Internals

### PR DESCRIPTION
**Pull request by RheagalFire**
### Description
merge Notebooks 17 and 19 

### Issue 
Closes #34

### CODE REVIEW

**Comment by NirantK** [comment]
This does not look like a merge but a plain deletion of one notebook? I don't see a section on special tokens in the updated and modified notebook

**Comment by NirantK** [comment]
And it needs to have the MLM task (BERT notebook?) covered in the same notebook as tokenizer, while the NWP prediction can go with special tokens since that ties into chat/instruction formatting.

**Comment by NirantK** [comment]
So this gets merged into 1 notebook: 

1. Tokens and Tokenizer
2. MLM and BERT
3. Next Word Prediction
4. Special Tokens and Instruction/Chat Format

**Review by NirantK — CHANGES_REQUESTED** [review]
1. Do not remove information
2. Re-organize as per the outline shared in comments

**Comment by RheagalFire** [comment]
> This does not look like a merge but a plain deletion of one notebook? I don't see a section on special tokens in the updated and modified notebook

The exact same section was already present in the notebook which is renamed.

**Comment by RheagalFire** [comment]
> So this gets merged into 1 notebook:
> 
> 1. Tokens and Tokenizer
> 2. MLM and BERT
> 3. Next Word Prediction
> 4. Special Tokens and Instruction/Chat Format

Done , can you check and LMK if everything looks good.

**Pull request merged**
